name: ALU CI

on:
  push:
  pull_request:

jobs:
  sim:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show tool versions
        run: |
          vsim -version

      - name: Run simulation
        run: vsim -c -do sim/run.do
        working-directory: ${{ github.workspace }}